# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Neighbor Ninja' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Neighbor Ninja
  use_frameworks!
  pod 'BTNavigationDropdownMenu'
  target 'Neighbor NinjaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Neighbor NinjaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
