# Uncomment this line to define a global platform for your project
platform :ios, '10.2'

target 'Neighbor Ninja' do
  pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'
  pod 'IQKeyboardManagerSwift'
  
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

end